// packages/dev/vue3/App.vue
<template>
  <div class="grid h-screen grid-rows-[auto,minmax(0,1fr)]">
    <div class="flex gap-4">
      <button @click="handleStart()">start</button>
      <button @click="handleNext()">next</button>
      <button @click="handleBack()">back</button>
      <button @click="handleExit()">exit</button>
    </div>
    <div class="relative flex flex-col gap-2 p-2">
      <div class="target1">target1</div>
      <div class="target2">target2</div>
      <div class="target3">target3</div>
      <Guider :steps="steps" :on-start="() => test()" ref="guider" />
    </div>
  </div>
</template>

<script setup lang="ts">
import Guider, { IGuider, Step } from "@vue3/index";
import { ref } from "vue";

const guider = ref<IGuider>();

const steps: Step[] = [
  { key: "target1", target: ".target1" },
  { key: "target2", target: ".target2" },
  { key: "target3", target: ".target3" },
];

const test = () => {
  console.log("test");
};

const handleStart = () => {
  guider.value.start();
};

const handleNext = () => {
  guider.value.next();
};

const handleBack = () => {
  guider.value.back();
};

const handleExit = () => {
  guider.value.exit();
};
</script>

// packages/dev/react/App.tsx
import { FC, useRef } from "react";
import Guider, { IGuider } from "@react/index";
import "../main.css";

const App: FC = () => {
  const guider = useRef<IGuider>();

  return (
    <div className="grid h-screen w-screen grid-rows-[auto,minmax(0,1fr)]">
      <div className="p-1">
        <div className="flex gap-2 p-1">
          <button onClick={() => guider.current.start()}>start</button>
          <button onClick={() => guider.current.next()}>next</button>
          <button onClick={() => guider.current.back()}>back</button>
          <button onClick={() => guider.current.exit()}>exit</button>
        </div>
      </div>
      <div className="relative bg-slate-50 p-4">
        <div className="target1 bg-sky-300 p-2">target1</div>
        <div className="target2 mt-4 bg-red-300 p-2">target2</div>
        <Guider
          ref={guider}
          steps={[
            {
              key: "target1",
              target: ".target1",
              onStepStart: (step) => console.log(`start ${step.key}`),
            },
            {
              key: "target2",
              target: ".target2",
              onStepExit: (step) => console.log(`exit ${step.key}`),
            },
          ]}
          onStart={() => console.log("start")}
          onExit={() => console.log("exit")}
        />
      </div>
    </div>
  );
};

export default App;
