// dev/react/src/App.tsx
import Guider, { IGuider } from "@react/index";
import { useRef } from "react";

function App() {
  const guider = useRef<IGuider>(null);
  return (
    <div className="grid h-screen w-screen grid-rows-[auto,minmax(0,1fr)]">
      <div className="p-1">
        <div className="flex gap-2 p-1">
          <button onClick={() => guider.current?.start()}>start</button>
          <button onClick={() => guider.current?.next()}>next</button>
          <button onClick={() => guider.current?.back()}>back</button>
          <button onClick={() => guider.current?.exit()}>exit</button>
        </div>
      </div>
      <div className="relative bg-slate-50 p-4">
        <div className="target1 bg-sky-300 p-2">target1</div>
        <div className="target2 mt-4 bg-red-300 p-2">target2</div>
        <Guider
          ref={guider}
          steps={[
            {
              key: "target1",
              target: ".target1",
              onStepStart: (step) => console.log(`start ${step?.key}`),
            },
            {
              key: "target2",
              target: ".target2",
              onStepExit: (step) => console.log(`exit ${step?.key}`),
            },
          ]}
          onStart={() => console.log("start")}
          onExit={() => console.log("exit")}
          popover={<div className="rounded-md bg-white p-2">popover</div>}
        />
      </div>
    </div>
  );
}

export default App;

// dev/vue3/src/App.vue
<script setup lang="ts">
import Guider, { IGuider, Step } from "@vue3/index";
import { ref } from "vue";

const guider = ref<IGuider>();
const steps: Step[] = [
  { key: "target1", target: ".target1" },
  { key: "target2", target: ".target2" },
];

const test = () => {
  console.log("test");
};

const handleStepStart = (step?: Step) => {
  console.log(step?.key);
};

const handleStart = () => {
  guider.value?.start();
};

const handleNext = () => {
  guider.value?.next();
};

const handleBack = () => {
  guider.value?.back();
};

const handleExit = () => {
  guider.value?.exit();
};
</script>

<template>
  <div class="grid h-screen grid-rows-[auto,minmax(0,1fr)]">
    <div class="flex gap-2 p-1">
      <button @click="handleStart()">start</button>
      <button @click="handleNext()">next</button>
      <button @click="handleBack()">back</button>
      <button @click="handleExit()">exit</button>
    </div>
    <div class="relative bg-slate-50 p-4">
      <div class="target1 bg-sky-300 p-2">target1</div>
      <div class="target2 mt-4 bg-red-300 p-2">target1</div>
      <Guider
        :steps="steps"
        :on-start="test"
        :on-step-start="handleStepStart"
        ref="guider"
      >
        <template #target1>
          <div class="rounded-md bg-white p-2">popover</div>
        </template>
        <template #target2>
          <div class="rounded-md bg-white p-2">popover target2</div>
        </template>
      </Guider>
    </div>
  </div>
</template>
